# Generated by Django 2.2.14 on 2020-08-13 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20200813_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='abstract',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
