# Generated by Django 2.2.14 on 2020-08-13 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_article_abstract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Author',
            new_name='author',
        ),
    ]
