# Generated by Django 2.2.14 on 2020-08-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20200813_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='delete_status',
        ),
        migrations.AddField(
            model_name='article',
            name='publish_status',
            field=models.BooleanField(choices=[(False, '未发布'), (True, '发布')], default=False, verbose_name='发布状态'),
        ),
    ]
